//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INF272_HA8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Franchise
    {
        public int FranchiseID { get; set; }
        public string FranchiseArea { get; set; }
        public string FranchiseName { get; set; }
        public string FranchiseOwner { get; set; }
        public string FranchiseNumberClients { get; set; }
    }
}
